[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "69af91535a9ef6133a814b9876fbc5404948cae0"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "ab6750ba1514101bb1741793a2bb5efcc8325fdfa562013c1e01f12568e0830e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "294b333950d7ef3a8ab63b2bc580481adb38bc65"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "8e44cb01b770c5f72f69364ed80d80a4b2d901beaa97489f2cd852ae71784ec4"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "cf251d1fcdbba0104d67fb99dcf5b0bd60d146b0"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "24f0a436f719bedf19d6f0c87f72c9b241afc597b373574fb50892789522c6ec"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "c007a20b99b316762091334a03ae2faaa741fe9f"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "fa1c2bda7fc8827c5e71e12aedb0ec194205a7523d4f774e3c342c8bd5549864"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "971944be8591a084b6004bdeb8cbf4939116b1ba"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "b8deb9cdf192634915728554ffc0ba880fad1dd2186f7cd1c6b3a35a7808e53e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "4a7545ad50c33bff2b63cecc67f14e102157f452"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "fbacf470eba1ad78efdacda4e489d6d2ab3857fe28f69dbb9e50b50b6be5eff3"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "9c9243802192ec6e867a6a78f8adb8e94f2588dd"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "64d5b421680f2a257e6efc0ecb3b29f89638b1194960ee2ba3f716c0bcf979a7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "a97f94ded10afe799afaf4c8a027333142f6a346"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "7c8831a8790610c983f2d6fbb233f8c1ab6778022248f25bbc2c72c11f2542fa"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "dd8c846e5b751c3eb33c691c8c8dbf3306e00f12"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "63b44c1356a18c5daf8bb5e3c709067f58cf2ff58e1b95eb0f611bffd623b2d7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "80c2cc0c829d56218d234963acbbca928bb8f17f"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "672b1329d02a2aa75af8f2348a2824bba128300a35665d73ad85e16c68d48111"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "cda2764e3e8c5eb152afa7d32cf25c8ff335f1d9"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "77c605eb474144911d4de7f0593e72f3ccf29fb62cf9982ffc9da2eabc08eaeb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "ba003308afde5073e599073010081982c7bb5ffc"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "928abeb4a8d0bf67f22f1eb6cc9b9ba67a87ef96353e06f2ae48b328d758064d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.0+0/SuiteSparse_GPU.v7.8.0.x86_64-linux-gnu-cuda+12.6.tar.gz"
