[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "2b57985b90b9530b840a633b23fd0981c368f62f"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "a43569d737f1adf9d09adf08b4cb87d39469d08b0e7dfe421500551e81eedb20"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "80aa1f4066573ed3b7581e247be9283d3635d96b"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "f376576f9e5fe69a89a00fe468121f1fd65cc4120a7a38fbb3b3dc410f566f2c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "aca1216f55a9e529c46ddbab26cc3681463c202a"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "4ed7aff4b9284736be7bbd2aa0a4bc4813b28191e87da7dd4d2759bafc641f50"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "5140d231a4a3f389130740424a3e7f4838d72c0d"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "83ef4f979fa7269cde74a6f71a5d54cbffde2e441a1557e311a7969d072ce209"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "b33d583ce121884b3fb378417051329c2b7606e4"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "05e89f5f5d7e4980ab358a1befb88298cc325437d08df82356d3d0b0feb68875"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "d15475a2797166567903d86f23a361a73d4f9e52"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "857e4f6b331cb2817b6697ff6876b44c953314dfde5c50f2dbcd5301c6d6b23f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "aed43ef448dc2343820f9bec4b5e9f966e17ce3e"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "211fae44973fafcf53ef0cf924cd15a603b20c7557472b8e6c4c30bc8f50fa9c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "8402ecc80a240e6f1a18237a4862db36c1400608"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "c21a0ef18d8688903c84d599513019a66c1a81fd4904db411347bf7b92a8f3b0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "da59c5e839941dbb112ce1782b1d28b60333dd18"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "b28e8e16fe639a52f2a1cbb880f9282d7da2b4d642df3250c2555fdb5e23eb97"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.6.0+0/SuiteSparse_GPU.v7.6.0.x86_64-linux-gnu-cuda+12.3.tar.gz"
