[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "11aff9edd8f2eb871b659f807f48a800d07f08ca"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "b9310adf841ade7bae78a82bdd17c726ec472e30b6c75b28277d31a6675215e5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+2/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "fa2b2e20beac1aa5d47d7eafd776462887c20651"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "a11683230e20903b72df2aaf870357ba215d3a97e150641b786cf3f44672e5b1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+2/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "d60b87dd33b0dd18571cd4ebd8f03b5f88971236"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "4ed900cfad6e235dfa58d135078486cec9e398a60d28c7d73f9fda1e2d6d4827"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+2/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
