[[SuiteSparse_GPU]]
arch = "x86_64"
git-tree-sha1 = "27d15bb27f2ffacb23002ed6a69dafeb1afb052c"
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "093317ea25a302208ba397f6420dd3ee186ea83768a3fa0ae054f27c35a170fb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.8.1+1/SuiteSparse_GPU.v5.8.1.x86_64-linux-gnu.tar.gz"
