[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "ebfce62b185469f6e58a7bd663ef98038f318c71"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "7d6fa8dc41fbea85c4482c4b2c89b82d5250c5533680002a80a70a179bfa1cab"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+1/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "f401c00e6b792aa108de26ead51d78e457a78e99"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "3753d9ef6d7dd51755966e692ef19e90b991ba0913111f1fffeb5c92f0335281"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+1/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "018dec47d4f12d479bf3c99fd92c293d61c7de1e"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "5aa3dd8e03e1432e69abc052a5a566666b6092fe03f0e801f115d6f37a53e9bf"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v5.10.1+1/SuiteSparse_GPU.v5.10.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
