[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "c798f7b372f6227a613d01163747b1b07557fdce"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "2078aa1895cbd2dd39516b6d6b748af4babc09a527009222b86ae388975d8f57"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "6d7b56fe54a9f20520f7466ca7ef82c7ec48c0e0"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "cf026f2f4be80cec435be4058d2262a547cdd5f653235fba9573a0d883e670a2"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "cced58f6eac9875fe7f6fad4bde7dca2e6443533"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "5a7bb9653c8090076d5064efaf54d9050b1f78aa9c8a660b01c33b231b4b3ec1"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "4ce0d7bcafba9b0c0d91cb8dd039299f31cd558d"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "9506a3abd128964475ede660ec978db6f396da52fe50f9143dd3a7652d5a6cf8"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "854b08e58a4f2c659d8a422071d06471ef4cc64d"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "48ffb21518d0056a3cb4528dc7ad9c948d5580afa7db81a3bbd43ce8a4f225fe"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "c618b09c588bb27e66ea8ad285cfe427dbee63ca"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "d21466ffd12328364180ae36dfffc40dd73be94ee5f7ac3836b863137d1c37fb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "f2be259e6150a621ff0536ec6f8b22d7447dfc40"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "a7ce1721e1309b20b38a56ec350ed8da6ee6e20e792b21bf442523ba6add85b0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "df6e76386585af8f0c5fcd22c3eb064a1433f0fe"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "17b40e73578436371f95fde1598c45e4b5bc94aa6bddaba9f967415393d64efd"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "bab696ac1c66b5f5708c0dfa575492f2616e59a2"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "c5089dc0b22d3cd3bffdae1570e9c5589e54617861adc36769c066125fd354a5"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "69347738506f6a300ea37b5c07fbce2657d22874"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "62afd32dd878f12c8b404994eac5577abe4777cc57a4844a170809fc2545cc9c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "b7978608012a10cd1b6271b3371ec16746807d37"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "480458d3abf487dfd41f543a304979c124412960316bf3dafe1df3c43d7ae5a0"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "00d896c41422861d7bb71f6eb70b1fe15acfb35d"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "19847d8c233d68067d5b33c4a498e752d5c83701e23b0852bea8fa54420c6993"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.8.3+0/SuiteSparse_GPU.v7.8.3.x86_64-linux-gnu-cuda+12.6.tar.gz"
