[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "613ce0675a6ed8605900f5ffb6662768af08c0c3"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "8deffaf91a8b2d70b2a05922d5bddcc12b7fbf8ce404f5e4a77a67db7ff87eca"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "1b89cb58a162a1b91caffa96b9bde1c3cbc9701d"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "d99c0a1762babac83f771b05bfb1b0c62c1c2b0b54946c605eadfbd3b11e344c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "2ff6172f158a518c9df08d0a0706c3299644c7a6"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "f91db91ec89b85c8ec64a91b9cec9de00637b0bf44aaa9cfe926dae07cec36cb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "cef6d4c74adf60dd924ad465107727b84bda7362"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "2823ef2a4de641e92995c9048a78aa50296e1c6543c1c0befd635261653715eb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "f547e5ba368daf02d454cfa68db780aabcf08e27"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "05c97711fdb3ce66bfec71d1ad4d07e47b45196c1fad37e58f3b76c210b9581f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "4a1b6ac51bf326b29aa87a69c6e22c5a1eee7871"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "2590a99fa19882b09c5ee2fdaa843eeca0415041bb0bfd40ad25e8e18487b3ac"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "26bc1ba188420cbc8f472d4e1459f506506fe35f"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "93f25ee1cb0236d0f542a8b1f1408c7f14b7795664a674eccab747ea787d1d9b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "3074fd36b492e8909a0a5a90803a31435b346fac"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "2efffb669f280a672eb2340d96a68c2026c76699a67120f251f0d1c6e7fa812c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "da961d3c6b4d3bdc0e99d3610633e87dd5eae7f6"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "97d5b8527cd87523e9b49ca87fbba35e1878aa2219e74f21dbf3d33fc99db56f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "73fe9d474a458c63d45c82120db0419caa822e65"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "8a3f04ded6e6d96e31456f1b2cba3c8a8859d2cb6ed9e0e7d3a20aec6ff44c83"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "f0bbf8e6102f28765a9a87cc4ee9ddd1385b85dd"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "5a4ffa7ab01b22e01bb379351a22df6da360d4a9ace9ad8488d6d4ad6bff93c7"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "43ed084fbf846934779823011e9db604170f87d6"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "39136376822ccbad041a3c8978df240da423d58a4afaba4464255672bc67581f"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "9afbffe108737981df58b142ccc11c2a5fa10483"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "d7934894af334ce3b9db7ef6abc09593bea779fa99363265fb3e4f462f957b95"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.10.1+0/SuiteSparse_GPU.v7.10.1.x86_64-linux-gnu-cuda+12.8.tar.gz"
