[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "018477af1812149175f4f343827536e710ab08b3"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "dc1c67a23d829dc2b5dd78b92ef45f5427a118368efe160c83eb9302fd1f6311"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "a1dbbc0f37b6603d1d453f51174b4b3051ce5b6a"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "7ab576fea6b4c20241e6efa505b04f6ead2776f54713704b6af7957274390c02"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "e752b2d572d5907699e07ea71942f305f1602a7e"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "08c2d5c28a5b218d1b8a2f222fa8458dc0ae37112189ebc7c75e99091506c61d"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "47e442f1f430f45db6de3c27717a37ae2558e7e9"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "c037e381ef3f065ca1a801528743c6ec47c8b47ec7927cbbda7e01777c31b287"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "391bae82b291df50f8b7bf0bb02934e0a8dbd008"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "a0ecec65f1d8c8dcdde0fad7b46e69b2e93dc061ec7f53fd246968b187169e0c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "b091228045d90ff2e68c19e425cbe12589f314c4"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "7c11122d8718a903ffc040738f28e533afba732ec8a6c5a596efd780368e77fc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "67d83af0df14f537ecec4ff4b6ab932b8b682d0d"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "a1d8e5e177a38929adf63f715753afb7cd2c5ced16ff268cda8402f8484c575e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "d8b5126c2e0304942c42949228e03bdfb96afaf7"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "e3dac704ca4e83a4b815bd7a730f4e60a4a1fb7cb2843b833b062de69ed3bdfd"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "73a68f549dabc914bafed70fb78c73a2b96f1bf8"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "f682a6dd5f081bce1f53c34ff39dd0c4b22f90f8e9ddaab21a255e3964d8832b"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "88b642278531fc4c5f8c82e08b81457e3d32a213"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "d56e5a0770987e44bbd1b30a7a0ad0c6e3148519e738454724ea50b038c38c4c"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "e4238bc650a8dc6b5519bade0b9b608f82b053da"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "d2bc32ad58f7a62cc8418b33a49f624b8a35d2103c4b1514e961f642d652e2eb"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.6"
git-tree-sha1 = "d98260f8b6a4c27b576269f2e73c26966bbb8497"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "5eff3b68503b403688c8c6022cac9bbf48bc64f598a89113c5ee86d457f05ccc"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.6.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.8"
git-tree-sha1 = "6050e6c4e5216195b07bb6b09df94d54527c4115"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "6eb8a9099d2a6a193879e2adab912f08e071f07b1e12424a21774e857435724e"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.8.tar.gz"
[[SuiteSparse_GPU]]
arch = "x86_64"
cuda = "12.9"
git-tree-sha1 = "a9e64486b831883810a052603190e82cfd92dbac"
lazy = true
libc = "glibc"
os = "linux"

    [[SuiteSparse_GPU.download]]
    sha256 = "28037a45354025c65c3c6dbe29feb1885cd82f82e648c50c533affa88b579d12"
    url = "https://github.com/JuliaBinaryWrappers/SuiteSparse_GPU_jll.jl/releases/download/SuiteSparse_GPU-v7.11.0+0/SuiteSparse_GPU.v7.11.0.x86_64-linux-gnu-cuda+12.9.tar.gz"
