# Autogenerated wrapper script for SuiteSparse_GPU_jll for x86_64-linux-gnu-cuda+11.0
export libGPUQREngine, libSuiteSparse_GPURuntime, libcholmod, libspqr, libsuitesparseconfig

using libblastrampoline_jll
using SuiteSparse_jll
using METIS_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("SuiteSparse_GPU")
JLLWrappers.@declare_library_product(libGPUQREngine, "libGPUQREngine.so.1")
JLLWrappers.@declare_library_product(libSuiteSparse_GPURuntime, "libSuiteSparse_GPURuntime.so.1")
JLLWrappers.@declare_library_product(libcholmod, "libcholmod.so.3")
JLLWrappers.@declare_library_product(libspqr, "libspqr.so.2")
JLLWrappers.@declare_library_product(libsuitesparseconfig, "libsuitesparseconfig.so.5")
function __init__()
    JLLWrappers.@generate_init_header(libblastrampoline_jll, SuiteSparse_jll, METIS_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libGPUQREngine,
        "lib/libGPUQREngine.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libSuiteSparse_GPURuntime,
        "lib/libSuiteSparse_GPURuntime.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcholmod,
        "lib/libcholmod.so.3",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspqr,
        "lib/libspqr.so.2",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsuitesparseconfig,
        "lib/libsuitesparseconfig.so.5",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
